### ISSUE TITLE
broken video file

### ISSUE THREAD

**Issue by HareshKarnan** [commaai/speedchallenge#2]
The video file train.mp4 appears to be broken. OpenCV throws the following error :

 [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fe761817c00] moov atom not found

Can this be fixed ?

**Comment by haraschax** [comment]
Not sure what you did, but this code works for me
```
import cv2
vidcap = cv2.VideoCapture('/home/batman/Downloads/test.mp4')
success,image = vidcap.read()
count = 0
while success:
  cv2.imwrite("frame%d.jpg" % count, image)     # save frame as JPEG file      
  success,image = vidcap.read()
  print('Read a new frame: ', success)
  count += 1
```

**Comment by swenkel** [comment]
@HareshMiriyala 

You have to make sure that you have installed [Git Large File Storage (git-lfs)](https://git-lfs.github.com/) to download both video files correctly.
