### ISSUE TITLE
Downloaded Files, MP4 Files not working

### ISSUE THREAD

**Issue by mralexcraven3** [commaai/speedchallenge#5]
Hello, 
I downloaded the files, unzipped it, and tried to open the .mp4 files. 
But it gives the error below:
**Can't play**
**This file isn’t playable. That might be because the file type is unsupported, the file extension is incorrect, or the file is corrupt.**
**0xc10100be**
See screenshot attached
<img width="1733" alt="can't open" src="https://user-images.githubusercontent.com/12472145/66723722-5d162600-ee14-11e9-929c-b0a9e0634be9.PNG">
Many thanks
Alex

**Comment by stfink** [comment]
See #2 
You need to install git lfs to unpack the mp4 correctly

**Comment by rickwierenga** [comment]
https://media.githubusercontent.com/media/commaai/speedchallenge/master/data/test.mp4
https://media.githubusercontent.com/media/commaai/speedchallenge/master/data/train.mp4

**Comment by x-N0** [comment]
![imagen](https://user-images.githubusercontent.com/51316342/95455940-93f61d80-093c-11eb-9b55-24f922a93014.png) So it finally worked? So close this.
