### ISSUE TITLE
Why use a camera in the first place?

### ISSUE THREAD

**Issue by SupreetKurdekar** [commaai/speedchallenge#9]
I recently came across this challenge and am really interested in trying to solve this problem. 

I have a question about the motivation though.

Why are we trying to predict the car speed using a  camera in the first place?
The speedometer will always be a better source of this information won't it?
And cars always have a speedometer, so why?

**Comment by haraschax** [comment]
Detecting absolute speed isn't necessarily that useful, but detecting 3D motion is. Our new challenge focuses more on that https://github.com/commaai/calib_challenge

This challenge was just designed to be a fun test of relevant skills.
